name: Accounting Tools
env_file:
  - .env
services:
  app:
    type: php:8.1
    via: cli
    composer_version: 2
    build_as_root:
      - echo "zend_extension=/user/Developer/miquelbrazil/accounting-tools/.lando/php/extensions/ioncube/ioncube_loader_lin_8.1.so" > /usr/local/etc/php/conf.d/00_docker-php-ext-ioncube_loader.ini
    build:
      - composer update
    config:
      php: .lando/php/php.ini
tooling:
  php:
    service: app
    cmd: php
  composer:
    service: app
    cmd: composer
    description: "Run Composer commands"
  console:
    service: app
    cmd: bin/console
